config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'hunters#show'
  resource :hunter, except: [:index] do
    collection do
      get 'progress'
      get 'hunting'
      get 'team'
    end
  end
  get     '/profile', to: 'hunters#show'

  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  match   '/forgot_password', to: 'sessions#forgot_password', via: [:get,:post]
  match   '/reset_password/:reset_token',  to: 'sessions#reset_password',  via: [:get,:post], as: 'reset_password'

  get     '/signup',  to: 'hunters#new'
  post    '/signup',  to: 'hunters#create'
end

app/models/hunter.rb
class Hunter < ApplicationRecord
  has_secure_password
  has_many :profile_records, dependent: :destroy

  validates :email, :profile_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, confirmation: true
  validates_with ProfileIdValidator, fields: [:profile_id]

  before_validation :strip_whitespace
  after_create :update_records

  def team_members
    Hunter.where({ team: team }).order(:name)
  end

  def update_records
    # This should be put else where (ie a rake task)
    record = profile_records.build

    doc = Nokogiri::HTML(open("https://www.mousehuntgame.com/profile.php?snuid=#{profile_id}"))

    camp_info = doc.css(".campLeft")

    # Breeds Info
    common_breeds_str, event_breeds_str = camp_info.css('.breedscaught').first.inner_html.split('<br>')

    common_breeds = common_breeds_str.match(/^Breeds\sCaught:\s(\d{1,3})\s\/\s(\d{1,3})$/)
    event_breeds  = event_breeds_str.match(/^Event\sBreeds\sCaught:\s(\d{1,3})\s\/\s(\d{1,3})$/)

    record.breeds_caught = common_breeds[1]
    record.breeds_total  = common_breeds[2]

    record.event_breeds_caught = event_breeds[1]
    record.event_breeds_total = event_breeds[2]

    # Run through the rest of the data
    camp_info.css('span.label').each do |label|
      param_name = label.text.strip.gsub(/[\s:"']/,'').underscore
      case param_name
      when "team"
        self.update_attribute(:team, label.next.text) if team != label.next.text
      when "hunting_since"
        self.update_attribute(:started_hunting, label.next.text) if started_hunting.blank?
      when "hunters_title"
        m = label.next.text.match(/^(.*)\s(?=\()\((\d+)%\)$/)
        record.title = m[1]
        record.title_progress = m[2]
      when "weapon"
        record.trap = label.next.text
      when "total_luck"
        record.trap_luck = label.next.text.to_i
      when "bait"
        if b = label.next.text.strip.match(/^(\d+)\spieces\sof\s(.+)$/)
          record.bait_name = b[2]
          record.bait_amount = b[1]
        else
          record.bait_name = 'None'
          record.bait_amount = 0
        end

      when "points", "gold", "horn_calls", "trap_power", "total_luck"
        record.send("#{param_name}=", label.next.text.gsub(',','').to_i)
      else
        record.send("#{param_name}=", label.next.text)
      end
    end
    record.save
    self.update_attribute(:last_scanned, Time.now)
  end

  def strip_whitespace
    self.name = self.name.strip unless self.name.nil?
    self.email = self.email.downcase.strip unless self.email.nil?
  end
end

app/controllers/hunters_controller.rb
class HuntersController < ApplicationController
  skip_before_action :require_hunter, only: [:new, :create]

  def new
    @hunter = Hunter.new
  end

  def create
    @hunter = Hunter.new(hunter_params)
    respond_to do |format|
      if verify_recaptcha(model: @hunter) && @hunter.save
        self.current_hunter = @hunter
        flash[:notice] = 'Welcome to Mousehunter Tracker'
        format.js { render js: "Turbolinks.visit('/')" }
        format.html { redirect_to profile_path }
      else
        format.js { render json: @hunter.errors, status: :unprocessable_entity }
        format.html { render 'new' }
      end
    end and return
  end

  def show
    @last_record = current_hunter.profile_records.last
  end

  def progress
    progress_attrs = [:gold,:points,:event_breeds_total,:event_breeds_caught, :breeds_caught, :breeds_total, :created_at, :location]
    @data = current_hunter.profile_records.select(progress_attrs).map{|pr| pr.attributes.merge({
      created_js_time: pr.created_js_time,
      location_image: pr.location_image
    })}
    respond_to do |format|
      format.json { render json: @data.to_json }
      format.html { redirect_to profile_path }
    end
  end

  def team
    team_attrs = [:gold,:points,:event_breeds_total,:event_breeds_caught, :breeds_caught, :breeds_total, :created_at, :location]

    @data = current_hunter.team_members.map { |tm|
      {
        id: tm.id,
        name: tm.name,
        records: tm.profile_records.select(team_attrs).map{|pr| pr.attributes.merge({created_js_time: pr.created_js_time })}
      }
    }
    respond_to do |format|
      format.json { render json: @data.to_json }
      format.html { redirect_to profile_path }
    end
  end

private
  def hunter_params
    p = params.require(:hunter).permit(:email, :password, :name, :password_confirmation, :profile_id)
  end
end

app/helpers/hunters_helper.rb
module HuntersHelper
end

app/views/hunters/_profile.html.haml
.row
  .col.m4.s12
    %h5 Status
    %table.striped
      %tbody
        %tr
          %td Title
          %td= "#{@last_record.title} (#{@last_record.title_progress}%)"
        %tr
          %td Team
          %td= current_hunter.team
        %tr
          %td Points
          %td= number_with_delimiter @last_record.points
        %tr
          %td Gold
          %td= number_with_delimiter @last_record.gold
  .col.m4.s12
    %h5 Hunting
    %table.striped
      %tbody
        %tr
          %td Horn Calls
          %td= number_with_delimiter @last_record.horn_calls
        %tr
          %td Breeds Caught
          %td= @last_record.breeds_caught
        %tr
          %td Breeds Total
          %td= @last_record.breeds_total
        %tr
          %td Event Breeds Caught
          %td= @last_record.event_breeds_caught
        %tr
          %td Event Breeds Total
          %td= @last_record.event_breeds_total
        %tr
          %td Mice Caught
          %td= number_with_delimiter @last_record.mice_caught

  .col.m4.s12
    %h5 Setup
    %table.striped
      %tbody
        %tr
          %td Location
          %td= @last_record.location
        %tr
          %td Region
          %td= @last_record.region
        %tr
          %td Trap
          %td= @last_record.trap
        %tr
          %td Base
          %td= @last_record.base
        %tr
          %td Charm
          %td= @last_record.charm
        %tr
          %td Bait
          %td= "#{number_with_delimiter(@last_record.bait_amount)} pieces of #{@last_record.bait_name}"
        %tr
          %td Trap Power
          %td= @last_record.trap_power
        %tr
          %td Trap Luck
          %td= @last_record.trap_luck

.row
  .col.m7.s12= render partial: 'layouts/change_log'

app/views/hunters/_progress.html.haml
.row
  .col.s12.m12
    #stats-graph


.row
  .col.s12.m12
    #normal-mice-graph

.row
  .col.s12.m12
    #event-mice-graph

app/views/hunters/_team.html.haml
.row
  .col.s12.m12
    #team-points-graph


.row
  .col.s12.m12
    #team-gold-graph

.row
  .col.s12.m12
    #team-mice-graph

.row
  .col.s12.m12
    #team-event-mice-graph

app/views/hunters/new.html.haml
.row
  .card-panel.session-card.col.m8.s12.offset-m2
    %h4.center-align Sign up
    = form_for @hunter, url: signup_path, method: :post, builder: StandardFormBuilder, html: { id: 'signup-form' } do |form|
      = render partial: 'layouts/error_messages', locals: { errors: form.object ? form.object.errors : [] }

      .input-field
        = form.text_field :email
        = form.label :email, class: form.object ? 'active' : ''
        We will never sell your email address, this is only used if you forget your password and need to reset it.
      .input-field
        = form.text_field :name
        = form.label :name, class: form.object ? 'active' : ''

      .input-field
        = form.password_field :password
        = form.label :password

      .input-field
        = form.password_field :password_confirmation
        = form.label :password_confirmation

      .input-field
        = form.text_field :profile_id
        = form.label :profile_id, "Mousehunt Profile ID", class: form.object ? 'active' : ''
        Get your profile ID by clicking on the Mousehunt shield and copy the snuid number from the address bar.
        %br
        eg. The profile ID for https://www.mousehuntgame.com/profile.php?snuid=123456789 would be 123456789
        %br

      .input-field= recaptcha_tags

      = submit_tag :submit, class: 'btn right'
    %br.clearfix
    %br

app/views/hunters/show.html.haml
%dl.right
  %dt Email
  %dd= current_hunter.email
  %dt Hunter ID
  %dd= current_hunter.profile_id
  %dt Profile Records
  %dd= current_hunter.profile_records.count
  %dt Last Scanned
  %dd= time_ago_in_words current_hunter.last_scanned


.row.clearfix
  .col.s12
    %ul.tabs
      %li.tab.col.s4
        %a.active{:href => "#profile"} Profile
      %li.tab.col.s4
        %a{:href => "#progress"} Your Progress
      %li.tab.col.s4
        %a{:href => "#team"} Team

#profile.col.s12= render partial: 'profile'

#progress.col.s12= render partial: 'progress'

#team.col.s12= render partial: 'team'