config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'hunters#show'
  resource :hunter, except: [:index] do
    collection do
      get 'progress'
      get 'hunting'
      get 'team'
    end
  end
  get     '/profile', to: 'hunters#show'

  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  match   '/forgot_password', to: 'sessions#forgot_password', via: [:get,:post]
  match   '/reset_password/:reset_token',  to: 'sessions#reset_password',  via: [:get,:post], as: 'reset_password'

  get     '/signup',  to: 'hunters#new'
  post    '/signup',  to: 'hunters#create'
end

app/views/layouts/_alert.html.haml
:javascript
  Materialize.toast("#{message}", 4000, "#{flash_class}")

app/views/layouts/_change_log.html.haml
%h5 Change Log
%p
  %strong 7th Feb, 2017, v1.05
  %br
  Permission for this app to function and scrape their website has been granted from the Moushunt Developers (HitGrab).
%p
  %strong 23rd Jan 2017, v1.05
  %br
  Added logo!
%p
  %strong 21st Jan 2017, v1.04
  %br
  Implemented Forgot Password link.
%p
  %strong 17th Jan 2017, v1.03
  %br
  Implemented Google Recaptcha on signups. Signups turned back on.
%p
  %strong 17th Jan 2017, v1.02.1
  %br
  Discovered over 15,000 fake users had been signed up via scripting. Signups turned off until a captcha can be implemented. All fake users have been deleted. My apologies for the inconvenience.
%p
  %strong 21st Dec 2016, v1.02
  %br
  Added Location icons to the graphs to show when a Hunter changes location.
%p
  %strong 20th Dec 2016, v1.01
  %br
  Switched graphing library from <a href="https://plot.ly">plot.ly</a> to <a href="https://highcharts.com">Highcharts.</a>
%p
  %strong 8th Dec 2016
  %br
  Version 1 released!

app/views/layouts/_error_messages.html.haml
.row
  .col.s12.item-errors{style: errors.blank? ? 'display:none' : ''}
    .card-panel.red.darken-3.white-text
      %h5 The following fields need to be fixed
      %ul
        - if errors.present?
          - errors.each do |error, message|
            %li
              = "#{error.to_s.humanize} #{message}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mousehunter Tracker
    = csrf_meta_tags

    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/
    %link{:href => "/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "/apple-touch-icon-57x57.png", :rel => "apple-touch-icon", :sizes => "57x57"}/
    %link{:href => "/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "/apple-touch-icon-76x76.png", :rel => "apple-touch-icon", :sizes => "76x76"}/
    %link{:href => "/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
    %link{:href => "/apple-touch-icon-120x120.png", :rel => "apple-touch-icon", :sizes => "120x120"}/
    %link{:href => "/apple-touch-icon-144x144.png", :rel => "apple-touch-icon", :sizes => "144x144"}/
    %link{:href => "/apple-touch-icon-152x152.png", :rel => "apple-touch-icon", :sizes => "152x152"}/
    %link{:href => "/apple-touch-icon-180x180.png", :rel => "apple-touch-icon", :sizes => "180x180"}/


    = stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://www.google.com/recaptcha/api.js', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://code.highcharts.com/highcharts.js', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://code.highcharts.com/modules/exporting.js', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'




  %body
    %nav
      .nav-wrapper.container
        %a.brand-logo{:href => "/"}
          Mousehunter Tracker

        - if current_hunter
          %ul.right.hide-on-med-and-down
            %li= link_to 'Logout', logout_path, method: :delete

    .container= yield

    = flash_messages



    %footer.page-footer
      .container
        Created by Chris Gooley, Logo by <a href="http://damienmason.com">Damien Mason</a>